import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';
import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/views/**/*.blade.php',
        './resources/js/**/*.js',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                border: 'hsl(var(--border))',
                foreground: 'hsl(var(--foreground))',
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                ring: 'hsl(var(--ring))',
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                'navy': '#0B1F3A',
                'secondary-fixed': '#e2e2e2',
                'on-secondary-fixed-variant': '#454747',
                'error-container': '#93000a',
                'on-tertiary-fixed-variant': '#44474c',
                'primary-fixed': '#cbf230',
                'tertiary-fixed-dim': '#c4c6cd',
                'on-primary-fixed-variant': '#3e4c00',
                'on-tertiary-container': '#61646a',
                'primary-fixed-dim': '#b0d500',
                'surface-bright': '#39393d',
                'tertiary-container': '#e0e2e9',
                'surface-container': '#1f1f23',
                'on-surface-variant': '#c5c9ae',
                'surface-container-high': '#2a292e',
                'secondary-container': '#454747',
                'on-tertiary': '#2d3136',
                'on-secondary-fixed': '#1a1c1c',
                'on-primary-container': '#586c00',
                'on-secondary': '#2f3131',
                'surface-container-lowest': '#0e0e12',
                'tertiary': '#cecece',
                'surface': '#131314',
                'error': '#ffb4ab',
                'tertiary-fixed': '#e2e2e9',
                'inverse-primary': '#536600',
                'surface-tint': '#e9c349',
                'on-error': '#690005',
                'on-background': '#e5e2e3',
                'on-tertiary-fixed': '#1a1c1c',
                'primary-container': '#d4af37',
                'secondary': '#e4c277',
                'on-primary': '#3c2f00',
                'surface-container-low': '#1c1b1c',
                'surface-dim': '#131314',
                'background': '#131314',
                'primary': '#f2ca50',
                'surface-variant': '#353436',
                'outline': '#99907c',
                'on-secondary-container': '#d5b46b',
                'outline-variant': '#4d4635',
                'on-surface': '#e5e2e3',
                'surface-container-highest': '#353436',
                'on-tertiary-container': '#444546',
                'inverse-surface': '#e5e2e3',
                'inverse-on-surface': '#313031',
                'on-primary-fixed': '#241a00',
                'on-error-container': '#ffdad6',
                'secondary-fixed-dim': '#e4c277',
                'on-primary-fixed-variant': '#574500',
                'primary-fixed': '#ffe088',
            },
            borderRadius: {
                'default': '0.25rem',
                'lg': '0.5rem',
                'xl': '0.75rem',
                'full': '9999px',
            },
            spacing: {
                'space-xs': '0.25rem',
                'space-sm': '0.5rem',
                'gutter-mobile': '1rem',
                'gutter': '2rem',
                'margin': '4rem',
                'space-md': '1rem',
                'margin-mobile': '1.5rem',
                'space-xl': '4rem',
                'space-lg': '2rem',
                'space-2xs': '0.125rem',
                'space-2xl': '4rem',
                'space-3xl': '6rem',
            },
            fontFamily: {
                'display-hero': ['"Plus Jakarta Sans"', 'sans-serif'],
                'title-editorial': ['"Plus Jakarta Sans"', 'sans-serif'],
                'headline-lg-mobile': ['"Plus Jakarta Sans"', 'sans-serif'],
                'headline-md': ['"Plus Jakarta Sans"', 'sans-serif'],
                'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
                'headline-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
                'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
                'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
                'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
                'label-caps': ['"Plus Jakarta Sans"', 'sans-serif'],
                'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
            },
            fontSize: {
                'body-md': ['clamp(0.875rem, 1.2vw, 1rem)', { lineHeight: '1.5', fontWeight: '400' }],
                'headline-md': ['clamp(1.25rem, 2vw, 1.75rem)', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-sm': ['clamp(1rem, 1.5vw, 1.25rem)', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
                'headline-xl-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-sm': ['clamp(0.75rem, 1vw, 0.875rem)', { lineHeight: '1.4', fontWeight: '400' }],
                'label-price': ['18px', { lineHeight: '22px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'display-hero-mobile': ['42px', { lineHeight: '46px', letterSpacing: '-0.03em', fontWeight: '700' }],
                'label-tech': ['11px', { lineHeight: '14px', letterSpacing: '0.08em', fontWeight: '500' }],
                'body-lg': ['clamp(1rem, 1.5vw, 1.25rem)', { lineHeight: '1.6', fontWeight: '300' }],
                'headline-xl': ['48px', { lineHeight: '54px', letterSpacing: '-0.03em', fontWeight: '700' }],
                'display-hero': ['clamp(3rem, 6vw, 6rem)', { lineHeight: '0.95', letterSpacing: '-0.02em', fontWeight: '700' }],
                'headline-lg': ['clamp(2rem, 4vw, 3.5rem)', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
                'title-editorial': ['clamp(1.5rem, 3vw, 2.5rem)', { lineHeight: '1.15', letterSpacing: '-0.01em', fontWeight: '400' }],
                'label-caps': ['clamp(0.65rem, 0.8vw, 0.75rem)', { lineHeight: '1', letterSpacing: '0.15em', fontWeight: '500' }],
                'label-sm': ['clamp(0.7rem, 0.9vw, 0.85rem)', { lineHeight: '1.2', fontWeight: '600' }],
            },
            animation: {
                'fade-in': 'fadeIn 0.6s ease-out',
                'fade-up': 'fadeUp 0.6s ease-out',
                'scale-in': 'scaleIn 0.3s ease-out',
                'slide-up': 'slideUp 0.4s ease-out',
                'marquee': 'marquee 25s linear infinite',
                'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
            },
            keyframes: {
                fadeIn: {
                    '0%': { opacity: '0' },
                    '100%': { opacity: '1' },
                },
                fadeUp: {
                    '0%': { opacity: '0', transform: 'translateY(20px)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                scaleIn: {
                    '0%': { opacity: '0', transform: 'scale(0.95)' },
                    '100%': { opacity: '1', transform: 'scale(1)' },
                },
                slideUp: {
                    '0%': { opacity: '0', transform: 'translateY(100%)' },
                    '100%': { opacity: '1', transform: 'translateY(0)' },
                },
                marquee: {
                    '0%': { transform: 'translateX(0)' },
                    '100%': { transform: 'translateX(-50%)' },
                },
            },
            boxShadow: {
                'soft': '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 1px 2px -1px rgba(0, 0, 0, 0.05)',
                'card': '0 1px 3px rgba(0, 0, 0, 0.06), 0 1px 2px rgba(0, 0, 0, 0.04)',
                'card-hover': '0 10px 25px -5px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
            },
        },
    },
    plugins: [forms, typography],
};
